%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_compile version 3.28.0

-ifndef(head_pb).
-define(head_pb, true).

-define(head_pb_gpb_version, "3.28.0").


-endif.
