-define(DEBUG(Label,Message), lager:debug(io_lib:format("~p ", [[Label]])++Message)).
-define(DEBUG(Label,Message, Args), lager:debug(io_lib:format("~p ", [[Label]])++Message, Args)).
-define(INFO(Label,Message), lager:info(io_lib:format("~p ", [[Label]])++Message)).
-define(INFO(Label,Message, Args), lager:info(io_lib:format("~p ", [[Label]])++Message, Args)).
-define(NOTICE(Label,Message), lager:notice(io_lib:format("~p ", [[Label]])++Message)).
-define(NOTICE(Label,Message, Args), lager:notice(io_lib:format("~p ", [[Label]])++Message, Args)).
-define(WARNING(Label,Message), lager:warning(io_lib:format("~p ", [[Label]])++Message)).
-define(WARNING(Label,Message, Args), lager:warning(io_lib:format("~p ", [[Label]])++Message, Args)).
-define(ERROR(Label,Message), lager:error(io_lib:format("~p ", [[Label]])++Message)).
-define(ERROR(Label,Message, Args), lager:error(io_lib:format("~p ", [[Label]])++Message, Args)).
-define(CRITICAL(Label,Message), lager:critical(io_lib:format("~p ", [[Label]])++Message)).
-define(CRITICAL(Label,Message, Args), lager:critical(io_lib:format("~p ", [[Label]])++Message, Args)).
-define(ALERT(Label,Message), lager:alert(io_lib:format("~p ", [[Label]])++Message)).
-define(ALERT(Label,Message, Args), lager:alert(io_lib:format("~p ", [[Label]])++Message, Args)).
-define(EMERGENCY(Label,Message), lager:emergency(io_lib:format("~p ", [[Label]])++Message)).
-define(EMERGENCY(Label,Message, Args), lager:emergency(io_lib:format("~p ", [[Label]])++Message, Args)).
-define(TEST_INFO(Message),lager:info(Message)).